### ISSUE TITLE
Navigation tabs have no active item marker

### ISSUE THREAD

**Issue by agamero-devo** [DevoInc/genesys-ui#63]
### What steps will reproduce the bug?

This is the current behavior of the component:
https://devoinc.github.io/genesys-ui/?path=/story/components-layout-applayout--double-navigation

### How often does it reproduce? Is there a required condition?

It always happens without any condition.

### What is the expected behavior? Why is that the expected behavior?

1. Navigation tabs should have a marker at the bottom when active.
<img width="770" alt="Screenshot 2024-07-31 at 07 44 06" src="https://github.com/user-attachments/assets/788e94d1-a231-4e30-9936-f91b821fbbae">

2. The marker displaces a smooth way between tabs when the active tab changes.

### What do you see instead?

There is no markers

**Comment by soslayando** [comment]
The AppLayout story for secondary navigation has been fixed
