### ISSUE TITLE
ReadOnly prop styles are not working

### ISSUE THREAD

**Issue by alberto-ag-devo** [DevoInc/genesys-ui#88]
### What steps will reproduce the bug?

[storybook](https://devoinc.github.io/genesys-ui/?path=/story/components-form-input--base&args=readOnly:!true)

### What do you see instead?

![image (15)](https://github.com/user-attachments/assets/ba0524fd-b7cb-4629-bf07-e82eb0c2e316)

left image: styles from genesys v12.3.1
right image: styles from genesys v11.1.1

**Comment by trigoporres** [comment]
version 12.4.0
