### ISSUE TITLE
Tables grow from 0 pixels to occupy the entire width, creating a strange visual effect.

### ISSUE THREAD

**Issue by alberto-ag-devo** [DevoInc/genesys-ui#92]
### What steps will reproduce the bug?

Create a BaseTable component with no width props.

### How often does it reproduce? Is there a required condition?

At the beginning the tables are created with width '0' and then grow to paint the columns, causing a strange visual effect.

### What do you see instead?

https://github.com/user-attachments/assets/bdf6b17d-9b9e-4f3c-ab2b-42a9b521cf1c

### Additional information

In previous versions of genesys like v11.1.1 using % in column widths making the width of the table add up to 100% this effects didn't appeared

**Comment by trigoporres** [comment]
version 12.4.1
