### ISSUE TITLE
Cells overlaps if setting width columns in pixels

### ISSUE THREAD

**Issue by alberto-ag-devo** [DevoInc/genesys-ui#93]
### What steps will reproduce the bug?

Create a BasicTable with a custom cell.
```
{
 cellRenderer: ({ rowIndex }: TCellRenderer) => renderCreateCollectorButton(rowIndex),
 id: COLUMN_NAMES.COLLECTOR_CREATE_INSTANCE_BUTTON,
 align: 'right' as TCellHorAlign,
},
```

### How often does it reproduce? Is there a required condition?

For this type of cells, if content is not able to contain the custom element, this overlaps with other cells.
Width property set in pixels is not sufficient if user changes the font size of the browser.

### What do you see instead?

With 150 pixels set to last column:
<img width="1582" alt="Captura de pantalla 2024-10-15 a las 13 41 34" src="https://github.com/user-attachments/assets/3f9d3d73-aadd-4a7e-9976-638ec6deb0df">

With the 150 pixels solution after changing font size:
<img width="1454" alt="Captura de pantalla 2024-10-15 a las 13 43 04" src="https://github.com/user-attachments/assets/bf5048f0-220a-499f-ae4b-88936cb830fb">

**Comment by trigoporres** [comment]
https://devoinc.github.io/genesys-ui/?path=/story/components-layout-table-cell-customcellrenderer--basic
