### ISSUE TITLE
When you select multiple items in a table filter, the filter selector box grows and overlaps with others filters selectors

### ISSUE THREAD

**Issue by adrianfega** [DevoInc/genesys-ui#95]
### What steps will reproduce the bug?

1. Create a table with several contiguous filter selectors (at least one multiple options filters)
2. In one of the multiple options selectors (except the last one) select several items, and you will see that the selector starts growing and overlaps with the next selector

### How often does it reproduce? Is there a required condition?

No, only contiguous filters, and at least one of them must be multiple options filter

### What is the expected behavior? Why is that the expected behavior?

No overlaps, the selector box must maintain its width despite the number of selected items

### What do you see instead?

Overlapped selectors

### Additional information

I attach a video of what happens

https://github.com/user-attachments/assets/d332e788-ffb9-4cc4-b593-dd059760be83

**Comment by soslayando** [comment]
Fixed in version 13.3.3
