### ISSUE TITLE
Table filter for numbers of 3 digits or more 

### ISSUE THREAD

**Issue by alberto-ag-devo** [DevoInc/genesys-ui#97]
### What is the problem this feature will solve?

Numbers with a x.y.z format may be filtered as numbers (Eg: A number such as 1.0.1 is greater than 1)

### What is the feature you are proposing to solve the problem?

Treat strings of numbers separated by commas to be accepted in the same way that numbers with or without decimals are filtered

**Comment by trigoporres** [comment]
I have created a storie as an example of custom filtering that you can use. When you confirm me what is needed I will close the issue.
https://devoinc.github.io/genesys-ui/?path=/docs/components-layout-table-filters--customfilters
