### ISSUE TITLE
Table cellEditor not works with select component

### ISSUE THREAD

**Issue by frandiaz92** [DevoInc/genesys-ui#98]
### What steps will reproduce the bug?

When implementing cell editor with a select component and if this select is configured with appendToBody=true, when selecting an option of the select it detects as if it is clicked out of the cell editor and exits the edit mode without triggering the callback onChange of the select.

### What do you see instead?

N/A

**Comment by frandiaz92** [comment]
Affected version: 12.1.2

**Comment by trigoporres** [comment]
https://devoinc.github.io/genesys-ui/?path=/docs/components-layout-table-editors-cellseditor--tablecelleditor

https://devoinc.github.io/genesys-ui/?path=/story/components-layout-table-editors-cellseditor--table-cells-editor

**Comment by trigoporres** [comment]
v13.5.0
