### ISSUE TITLE
Add the data-testid to the table component.

### ISSUE THREAD

**Issue by Pedro-devo15** [DevoInc/genesys-ui#99]
### What is the problem this feature will solve?

Solved the tests that we are using in the QA projects

### What is the feature you are proposing to solve the problem?

Add the data-testid to the table in order to use it in the actual test (as we did with COCO)

**Comment by trigoporres** [comment]
Following w3c standards we have added props:
- aria-colindex
- aria-rowindex
- aria-colcount
- aria-rowcount

With that we consider that there are enough identifiers to be able to access the components and test them.
